spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: pwd
    url: jdbc:mysql://localhost:3306/java_study
    username: root
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
    open-in-view: true